# Generated by Django 5.2 on 2025-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_occupation'),
        ('posts', '0003_post_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='posts.tag'),
        ),
    ]
