# Generated by Django 4.1.13 on 2025-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, default='Developer', max_length=100),
        ),
    ]
