# Generated by Django 4.1.13 on 2025-04-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tech_stack',
            field=models.TextField(default='N/A'),
        ),
    ]
