# Generated by Django 5.2 on 2025-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
