# Generated by Django 5.2 on 2025-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tech_stack',
            field=models.TextField(default='N/A', null=True),
        ),
    ]
